[package]
name = "token_launcher"
version = "1.0.0"
authors = ["pedestri <pedro@hackachain.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = {version = "4.0.0", features = ["unstable"]}
near-contract-standards = "4.0.0"