[package]
name = "modified-contract-standards"
version = "1.0.0"
authors = ["Near Inc <hello@near.org>", "Hack-aChain Software <joao@hackachain.io>"]
edition = "2018"
categories = ["wasm"]
description = """
NEAR smart contracts standard library modified for the purposes of this project.
"""

[dependencies]
near-sdk = "3.1.0" 
serde = "1"
serde_json = "1"