version: "3.9"
services:
  web:
    build:
      context: ../../.
      dockerfile: ./services/web/Dockerfile
    ports:
      - "3000:3000"
  
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5438:5432"

  graphql:
    build:
      context: ../../.
      dockerfile: ./services/graphql/Dockerfile
    ports: 
      - "4000:4000"
  
  indexer:
    build:
        context: ../../.
        dockerfile: ./services/indexer-ts/Dockerfile
    volumes:
      - ~/.aws/:/root/.aws:ro