name: Tertnet Vercel Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TESTNET_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_TESTNET_PROJECT_ID }}
on:
  pull_request:
    types:
      - closed
    branches:
      - testnet-version

jobs:
  vercel_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@canary

      - name: Set Testnet environemnt variables
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TESTNET_TOKEN }}
      
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TESTNET_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TESTNET_TOKEN }}