name: Tertnet Vercel Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TESTNET_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_TESTNET_PROJECT_ID }}
  VITE_GRAPHQL_API_URI: https://jacksondev.xyz/
on: pull_request
  # pull_request:
    # types:
    #   - closed
    # branches:
    #   - testnet-version

jobs:
  vercel_deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      
      - name: Install Yarn Globally
        run: npm install -g yarn

      - name: Installing Dependencies
        run: yarn

      - name: Set Testnet environment variables
        run: yarn run setup:testnet:web
      
      - name: Pull vercel setup
        run: vercel pull --yes --token=${{ secrets.VERCEL_TESTNET_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TESTNET_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TESTNET_TOKEN }}