[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
near-lake-framework = "0.5.0"

# Serialization/Deserialization
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.55"
strum = { version = "0.24", features = ["derive"] }

# Async runtime
futures = "0.3.5"
tokio = { version = "1.1", features = ["sync", "time", "macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1" }

# Postgres
tokio-postgres = { version = "0.7.6", features = ["with-chrono-0_4"] }
bb8 = "0.8.0"
bb8-postgres = "0.8.1"
postgres-types = { version = "0.2.3", features = ["derive"] }
chrono = "0.4"
rust_decimal = { version = "1.25", features = ["db-tokio-postgres"] }

# Config & Logging
dotenv = "0.15.0"
once_cell = "1.13.0"

tracing = "0.1.13"
tracing-subscriber = "0.3.14"

# Utils
vec_box = "1.0.0"
