[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
near-indexer = { git = "https://github.com/near/nearcore", rev = "ac2a43e26065a354c1b0f896d4259967e4757d38" }

actix = "=0.13.0"
actix-web = "=4.1.0"
actix-http = "^3.0.0"
actix-tls = "=3.0.3"
actix_derive = "=0.6.0"
openssl-probe = { version = "0.1.2" }
r2d2 = "0.8.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.55"
tokio = { version = "1.1", features = ["sync", "time"] }
